=== Piecelet/neodb-public-api/data/servers/schema.json
{
    "name": "NeoDB Public Instance Info Schema",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
      "domain": {
        "type": "string"
      },
      "version": {
        "type": "string"
      },
      "title": {
        "type": "string"
      },
      "description": {
        "type": "string"
      },
      "languages": {
        "type": "array",
        "items": [
          {
            "type": "string"
          }
        ]
      },
      "display_languages": {
        "type": "array",
        "items": [
          {
            "type": "string"
          }
        ]
      },
      "region": {
        "type": "string"
      },
      "display_region": {
        "type": "string"
      },
      "categories": {
        "type": "array",
        "items": [
          {
            "type": "string"
          }
        ]
      },
      "proxied_thumbnail": {
        "type": "string"
      },
      "blurhash": {
        "type": "string"
      },
      "icon": {
        "type": "string"
      },
      "logo": {
        "type": "string"
      },
      "total_users": {
        "type": "integer"
      },
      "last_week_users": {
        "type": "integer"
      },
      "approval_required": {
        "type": "boolean"
      },
      "language": {
        "type": "string"
      },
      "display_language": {
        "type": "string"
      },
      "category": {
        "type": "string"
      }
    },
    "required": [
      "domain",
      "version",
      "description",
      "languages",
      "display_languages",
      "region",
      "categories",
      "proxied_thumbnail",
      "blurhash",
      "total_users",
      "last_week_users",
      "approval_required",
      "language",
      "category",
      "title"
    ]
  }

=== Piecelet/neodb-public-api/data/servers/servers-community.json
[
  {
    "domain": "reviewdb.app",
    "version": "4.0.4 (compatible; NeoDB 0.16.2-9a195e4-20260615193459)",
    "description": "Reviews about book, film, music, podcast and game.",
    "languages": [
      "en"
    ],
    "display_languages": [
      "English"
    ],
    "region": "",
    "categories": [
      "general"
    ],
    "proxied_thumbnail": "https://reviewdb.app/static/img/fjords-banner-600.fa337a5055b6.jpg",
    "blurhash": "",
    "icon": "https://reviewdb.app/icon.png",
    "total_users": 160,
    "last_week_users": 0,
    "approval_required": false,
    "language": "en",
    "display_language": "English",
    "category": "general",
    "title": "ReviewDB",
    "logo": "https://reviewdb.app/logo.png"
  },
  {
    "domain": "minreol.dk",
    "version": "neodb/dev",
    "description": "Reviews about book, film, music, podcast and game.",
    "languages": [
      "en"
    ],
    "display_languages": [
      "English"
    ],
    "region": "europe",
    "display_region": "Europe",
    "categories": [
      "general"
    ],
    "proxied_thumbnail": "https://minreol.dk/static/img/fjords-banner-600.fa337a5055b6.jpg",
    "blurhash": "",
    "icon": "https://minreol.dk/icon.png",
    "total_users": 123,
    "last_week_users": 0,
    "approval_required": false,
    "language": "en",
    "display_language": "English",
    "category": "general",
    "title": "Minreol",
    "logo": "https://minreol.dk/logo.png"
  },
  {
    "domain": "neodb.kevga.de",
    "version": "4.0.4 (compatible; NeoDB 0.14.1.2-3ce2612-135725d-20260503020832)",
    "description": "Reviews about book, film, music, podcast and game.",
    "languages": [
      "en"
    ],
    "display_languages": [
      "English"
    ],
    "region": "europe",
    "display_region": "Europe",
    "categories": [
      "general"
    ],
    "proxied_thumbnail": "https://neodb.kevga.de/static/img/fjords-banner-600.fa337a5055b6.jpg",
    "blurhash": "",
    "icon": "https://neodb.kevga.de/icon.png",
    "total_users": 52,
    "last_week_users": 0,
    "approval_required": false,
    "language": "en",
    "display_language": "English",
    "category": "general",
    "title": "Kevga NeoDB",
    "logo": "https://neodb.kevga.de/logo.png"
  },
  {
    "domain": "fantastika.social",
    "version": "4.0.4 (compatible; NeoDB 0.14.1.2-3ce2612-135725d-20260503020832)",
    "description": "Comunidad hispanohablante de NeoDB para registrar, valorar y compartir libros, películas, música, juegos y podcasts.",
    "languages": [
      "en"
    ],
    "display_languages": [
      "English"
    ],
    "region": "",
    "categories": [
      "general"
    ],
    "proxied_thumbnail": "https://media.fantastika.social/config/2025/2/28/Z1Usn6g0S5l8jtgucRqrmQ9Qw8U.png",
    "blurhash": "",
    "icon": "https://fantastika.social/s/img/icon.png",
    "total_users": 39,
    "last_week_users": 0,
    "approval_required": false,
    "language": "en",
    "display_language": "English",
    "category": "general",
    "title": "Fantastika",
    "logo": "https://fantastika.social/s/img/logo.svg"
  },
  {
    "domain": "lib.itinerariummentis.org",
    "version": "neodb/dev-unknown",
    "description": "Itinerarium in Librarium Mentis",
    "languages": [
      "en"
    ],
    "display_languages": [
      "English"
    ],
    "region": "",
    "categories": [
      "general"
    ],
    "proxied_thumbnail": "https://lib.itinerariummentis.org/media/config/2025/3/12/bONLPUrBzHytTZk1i3Poaw7xKQk.png",
    "blurhash": "",
    "icon": "https://lib.itinerariummentis.org/icon.png",
    "total_users": 10,
    "last_week_users": 0,
    "approval_required": false,
    "language": "en",
    "display_language": "English",
    "category": "general",
    "title": "Itinerariummentis Lib",
    "logo": "https://lib.itinerariummentis.org/logo.png"
  },
  {
    "domain": "polg.cn",
    "version": "4.0.4 (compatible; NeoDB 0.14.1.2-3ce2612-135725d-20260503020832)",
    "description": "专注书籍、电影、音乐收藏与评论的联邦宇宙社区",
    "languages": [
      "en"
    ],
    "display_languages": [
      "English"
    ],
    "region": "asia",
    "display_region": "Asia",
    "categories": [
      "general"
    ],
    "proxied_thumbnail": "https://i.polg.cn/config/2026/4/10/D-D7pmHPvd_OzP5LNoX2x3LtpKU.webp",
    "blurhash": "",
    "icon": "https://polg.cn/favicon.ico",
    "total_users": 5,
    "last_week_users": 0,
    "approval_required": false,
    "language": "en",
    "display_language": "English",
    "category": "general",
    "title": "Polg",
    "logo": "https://polg.cn/logo.png"
  },
  {
    "domain": "crititeca.illustietor.com",
    "version": "4.0.4 (compatible; NeoDB 0.16-cf66fc6-20260612202423)",
    "description": "Reviews about book, film, music, podcast and game.",
    "languages": [
      "en"
    ],
    "display_languages": [
      "English"
    ],
    "region": "",
    "categories": [
      "general"
    ],
    "proxied_thumbnail": "https://crititeca.illustietor.com/static/img/fjords-banner-600.fa337a5055b6.jpg",
    "blurhash": "",
    "icon": "https://crititeca.illustietor.com/icon.png",
    "total_users": 4,
    "last_week_users": 0,
    "approval_required": false,
    "language": "en",
    "display_language": "English",
    "category": "general",
    "title": "Illustietor Crititeca",
    "logo": "https://crititeca.illustietor.com/logo.png"
  },
  {
    "domain": "watch.socialyeti.club",
    "version": "neodb/0.12.8-cccec03-5d1d336-20260112133518",
    "description": "Reviews about book, film, music, podcast and game.",
    "languages": [
      "en"
    ],
    "display_languages": [
      "English"
    ],
    "region": "",
    "categories": [
      "general"
    ],
    "proxied_thumbnail": "https://watch.socialyeti.club/static/img/fjords-banner-600.fa337a5055b6.jpg",
    "blurhash": "",
    "icon": "https://watch.socialyeti.club/yeti-watch-icon.png",
    "total_users": 3,
    "last_week_users": 0,
    "approval_required": false,
    "language": "en",
    "display_language": "English",
    "category": "general",
    "title": "Socialyeti Watch",
    "logo": "https://watch.socialyeti.club/yeti-watch.png"
  },
  {
    "domain": "film.upstairs.cn",
    "version": "neodb/0.12.9-cccec03-9fc8408-20260201190749",
    "description": "Reviews about book, film, music, podcast and game.",
    "languages": [
      "en"
    ],
    "display_languages": [
      "English"
    ],
    "region": "asia",
    "display_region": "Asia",
    "categories": [
      "general"
    ],
    "proxied_thumbnail": "https://film.upstairs.cn/media/config/2026/3/22/nOzQtoRKx_uS38XtPZr_MebbzLw.jpeg",
    "blurhash": "",
    "icon": "https://film.upstairs.cn/favicon.ico",
    "total_users": 1,
    "last_week_users": 0,
    "approval_required": false,
    "language": "en",
    "display_language": "English",
    "category": "general",
    "title": "Upstairs Film",
    "logo": "https://film.upstairs.cn/logo.png"
  },
  {
    "domain": "db.casually.cat",
    "version": "",
    "title": "Casually DB",
    "description": "",
    "languages": [],
    "display_languages": [],
    "region": "",
    "categories": [],
    "proxied_thumbnail": "https://neodb.internal/placeholder",
    "blurhash": "",
    "total_users": 0,
    "last_week_users": 0,
    "approval_required": false,
    "language": "",
    "category": ""
  },
  {
    "domain": "garage.o00o.lol",
    "version": "",
    "title": "O00o Garage",
    "description": "",
    "languages": [],
    "display_languages": [],
    "region": "",
    "categories": [],
    "proxied_thumbnail": "https://neodb.internal/placeholder",
    "blurhash": "",
    "icon": "https://garage.o00o.lol/icon.png",
    "total_users": 0,
    "last_week_users": 0,
    "approval_required": false,
    "language": "",
    "category": "",
    "logo": "https://git.o00o.lol/admin/image-garage/raw/branch/main/logo.png"
  },
  {
    "domain": "log.melonbread.xyz",
    "version": "",
    "title": "Melonbread Log",
    "description": "",
    "languages": [],
    "display_languages": [],
    "region": "",
    "categories": [],
    "proxied_thumbnail": "https://neodb.internal/placeholder",
    "blurhash": "",
    "total_users": 0,
    "last_week_users": 0,
    "approval_required": false,
    "language": "",
    "category": ""
  },
  {
    "domain": "neodb.mastodon.work",
    "version": "",
    "title": "Mastodon NeoDB",
    "description": "",
    "languages": [],
    "display_languages": [],
    "region": "",
    "categories": [],
    "proxied_thumbnail": "https://neodb.internal/placeholder",
    "blurhash": "",
    "total_users": 0,
    "last_week_users": 0,
    "approval_required": false,
    "language": "",
    "category": ""
  },
  {
    "domain": "neodb.neo-cities.homes",
    "version": "",
    "title": "Neo-cities NeoDB",
    "description": "",
    "languages": [],
    "display_languages": [],
    "region": "",
    "categories": [],
    "proxied_thumbnail": "https://neodb.internal/placeholder",
    "blurhash": "",
    "total_users": 0,
    "last_week_users": 0,
    "approval_required": false,
    "language": "",
    "category": ""
  },
  {
    "domain": "neodb.nickfi.de",
    "version": "",
    "title": "Nickfi NeoDB",
    "description": "",
    "languages": [],
    "display_languages": [],
    "region": "",
    "categories": [],
    "proxied_thumbnail": "https://neodb.internal/placeholder",
    "blurhash": "",
    "total_users": 0,
    "last_week_users": 0,
    "approval_required": false,
    "language": "",
    "category": ""
  },
  {
    "domain": "neodb.versi-tech.com",
    "version": "",
    "title": "Versi-tech NeoDB",
    "description": "",
    "languages": [],
    "display_languages": [],
    "region": "",
    "categories": [],
    "proxied_thumbnail": "https://neodb.internal/placeholder",
    "blurhash": "",
    "total_users": 0,
    "last_week_users": 0,
    "approval_required": false,
    "language": "",
    "category": ""
  }
]

=== Piecelet/neodb-public-api/data/servers/servers-official.json
[
  {
    "domain": "neodb.social",
    "version": "4.0.4 (compatible; NeoDB 0.16.5-3a4faad-20260716193842)",
    "description": "一个自由、开放、互联的书籍、电影、音乐和游戏收藏评论交流社区",
    "languages": [
      "en"
    ],
    "display_languages": [
      "English"
    ],
    "region": "",
    "categories": [
      "general"
    ],
    "proxied_thumbnail": "https://neodb.social/media/config/2024/1/15/ee3zCNw6BrMp2DW3nH8b4fEO_m4.png",
    "blurhash": "",
    "icon": "https://neodb.social/s/img/icon.png",
    "total_users": 33837,
    "last_week_users": 0,
    "approval_required": false,
    "language": "en",
    "display_language": "English",
    "category": "general",
    "title": "NeoDB",
    "logo": "https://neodb.social/s/img/logo.svg"
  },
  {
    "domain": "eggplant.place",
    "version": "4.0.4 (compatible; NeoDB main-0e345de-20260717024821)",
    "description": "Reviews about book, film, music, podcast and game.",
    "languages": [
      "en"
    ],
    "display_languages": [
      "English"
    ],
    "region": "",
    "categories": [
      "general"
    ],
    "proxied_thumbnail": "https://eggplant.place/media/config/2024/1/15/zSi9h6bAWx05WG0QFjRglP47HCs.webp",
    "blurhash": "",
    "icon": "https://eggplant.place/logo2.png",
    "total_users": 862,
    "last_week_users": 0,
    "approval_required": false,
    "language": "en",
    "display_language": "English",
    "category": "general",
    "title": "Eggplant",
    "logo": "https://eggplant.place/logo2.png"
  }
]
